### ISSUE TITLE
broken link in readme

### ISSUE THREAD

**Issue by japhir** [UtrechtUniversity/summer-fair#6]
In the readme on https://github.com/UtrechtUniversity/summer-fair#manual, it links to https://github.com/UtrechtUniversity/summer-fair/blob/master/link but this link is broken.

I've tried to install jupyter notebook and all the other things listed in the next sentence and clicked the link again but it still goes to 404.

**Comment by eslavco** [comment]
Hi Ilja, 

We have fix the link. We have refactored the code and didn't yet update the Jupyter notebook according to new changes. 
Will let you know, once it is updated.
